name: CI
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        run: |
          rm -rf ${{github.event.repository.name}}
          git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}
          git -C "${{github.workspace}}/${{github.event.repository.name}}" checkout ${{github.ref}}
      - name: ThreadPool unittest
        run: |
          sudo apt install googletest libgtest-dev
          cd ${{github.event.repository.name}}
          mkdir build && cd build
          cmake ..
          make
          ./tests/test
      - name: Cleanup
        run: |
          rm -rf ${{github.event.repository.name}}